### ISSUE TITLE
Treaty Output

### ISSUE THREAD

**Issue by punbro** [Juris-M/legal-resource-registry#20]
I am trying to output footnote for Treaties and other UN instruments using AGLC4 which Jurism is not outputting correctly... AGLC4 suggests Treaty should be cited as: _Treaty Title_, opened for signature Date, Treaty Series (entered into force Date). Please help!

**Comment by fbennett** [comment]
AGLC4 is a Zotero style maintained by the Zotero community. For help with it, please post to the forums there, on https://forums.zotero.org/
