### ISSUE TITLE
Default language is not reachable

### ISSUE THREAD

**Issue by georgd** [Juris-M/legal-resource-registry#23]
Since the great new developments, it’s no longer possible to use the default language in citations if a second language is defined. Using the appended record as input together with jm-indigobook-law-review and the document language in Word set to en-US, I receive the following output:

`Crown Forest Industries Ltd. v. Canada, Tax Treaty Case Law IBFD (CSC Jun. 22, 1995).`

The court abbreviation should read `SCC` instead of `CSC`.

```json
[
  {
    "type": "legal_case",
    "title": "Crown Forest Industries Ltd. v. Canada",
    "authority": "Supreme Court",
    "issued": {
      "date-parts": [
        [
          1995,
          6,
          22
        ]
      ]
    },
    "shortTitle": "Crown Forest",
    "note": "",
    "multi": {
      "main": {},
      "_keys": {}
    },
    "archive": "Tax Treaty Case Law IBFD",
    "jurisdiction": "ca"
  }
]
```

**Comment by fbennett** [comment]
This is our language arbitration bug at work.
https://github.com/Juris-M/citeproc-js/issues/151

**Comment by fbennett** [comment]
Closing this, as the bug is in Jurism, ``citeproc-js`` and the Abbrevs Filter, not the LRR itself.

**Comment by fbennett** [comment]
Popping this open to say that a [Jurism beta 5.0.90m7](https://our.law.nagoya-u.ac.jp/jurism/dl?channel=beta&amp;platform=mac) beta is out, with a fix for locale arbitration of jurisdiction abbrev lists (and then close again...)
