### ISSUE TITLE
UI language not displaying

### ISSUE THREAD

**Issue by Droitslinguistiques** [Juris-M/legal-resource-registry#27]
Hello! I've been testing a new set of abbreviations for Canada. I set a "fr" variant for every jurisdiction and court in the "auto-ca" file. 

However, when using Juris-M, even with the app set to french, the english names are still displayed in the UI.

Have I missed something in setting up the french names?

**Comment by fbennett** [comment]
Your latest ``juris-fr-desc.json`` source compiles and runs nicely in the client. (The ``auto-ca.json`` and ``auto-ca-fr.json`` files are generated automatically.) To set up, I have something like this in my home-directory ``~/.jurisUpdate`` config file:
```
{
  "path": {
    "dataDir": null,
    "jurisAbbrevsDir": "/path/to/jurism/data/dir/juris-abbrevs",
    "jurisMapDir": "/path/to/jurism/data/dir/jurism/juris-maps",
    "jurisSrcDir": "/path/to/lrr/source/repo/juris-desc/src"
  }
}
```
Running ``jurisupdate`` updates the abbrev and UI menu map files and bumps their versions. If all goes well, the changes will be picked up by the client when it is restarted. If that doesn't work, let me know: my setup is slightly different, updating into a source repo from which I build build and run a fresh copy of the client. But it's *intended* that updates into the Jurism data dir, without a client rebuild, will also work.

**Comment by Droitslinguistiques** [comment]
I have run jurisupdate, and I manually checked the map and abbrev files in my Jurism data directory, and I've confirmed that they are correct and updated.

However, when I launched Jurism, the UI court and jurisdiction names in the citation items are still displaying in english. 

Actually, it is weirder than that. For exemple, if I select "Ontario" as the jurisdiction, and then press the down arrow under "Tribunal", the drop down list is in english. However, whenever I select one of them, the court is then highlighted in yellow, as if it was an unrecognized court. 

So not only are the french versions not showing up for me, the selections that are available for the drop down menu aren't getting recognized as valid.

**Comment by fbennett** [comment]
What is your installed Jurism version?

**Comment by Droitslinguistiques** [comment]
5.0.90m3

**Comment by fbennett** [comment]
That would be the cause---the language arbitration smarts had only been added to the beta. A fresh release just went up though (5.0.90m4 / 5.0.90m5 on the Mac) that incorporates the changes. If you update the client, it should behave better.

**Comment by Droitslinguistiques** [comment]
Fantastic! 

So I just did the update. The good news is that the french version of the court names is showing up in the drop down list. However, when selected, it is still displaying in yellow, as it would if it was an incorrect name.

**Comment by Droitslinguistiques** [comment]
Just did the update!

The court name are displaying in the correct language! However, I am unable to get the french name of the canadian subjuridictions provinces to show up in french.

**Comment by fbennett** [comment]
Good news as far as it goes! Still some work to do then, it seems.

**Comment by Droitslinguistiques** [comment]
I think there may be some relation between this and the other issue I've opened.

Nowhere in the map file are the jurisdiction variant `name` values noted, whereas the variant `name` of courts are. Could that be part of the problem?

**Comment by Droitslinguistiques** [comment]
> Good news as far as it goes! Still some work to do then, it seems.

Yeah! Still a fantastic update! Displaying the court names in French is already a massive leap forward.

**Comment by fbennett** [comment]
Yes, that's exactly it. Jurisdictions are not yet locale-aware.

**Comment by fbennett** [comment]
Ha. In the code, I discovered that I *intended* to make jurisdiction names locale-aware, but the variants were just being skipped because of a typo. This will work in the next release.
