### ISSUE TITLE
Whether to translate all courts or only ones with multiple official languages

### ISSUE THREAD

**Issue by Droitslinguistiques** [Juris-M/legal-resource-registry#29]
Hello! I'm very sorry for starting a new issue, but this didn't seem directly related to either of my other two open issues.

I'm wondering if there is an establish standard for which court names should be translated in the UI, or whether they should all be translated.

I ask because there are two ways to translate a court name. Either by:

1) Setting a variant `name` in the `courts` object, or 
2) Only setting a variant `name` in the `court` object when called in multilingual jurisdiction. 

For exemple, Alberta and New Brunswick both have a "Court of Appeal". However, Alberta is unilingual English, whereas New Brunswick is officially bilingual french/english.

If I want "Court of Appeal" to always display as "Cour d'appel", then I can set the name in the `court` object:

```
  courts": {
    "court.appeal": {
      "name": "Court of Appeal",
      "variants": {
        "fr": {
          "name": "Cour d'appel"
        }
      }
    },
  "jurisdictions": {
    "ca:ab": {
      "name": "Alberta",
      "courts": {
        "court.appeal": {},
      }
    },
    "ca:nb": {
      "name": "New-Brunswick",
      "courts": {
        "court.appeal": {}
      }
    },
```

However, if I would rather that "Cour d'appel" ONLY shows up in the jurisdictions that are bilingual, I would not put a variant `name` in the court object, but rather, in each court call in a bilingual jurisdiction. 

```
  "courts": {
    "court.appeal": {
      "name": "Court of Appeal",
      }
    },
  "jurisdictions": {
    "ca:ab": {
      "name": "Alberta",
      "courts": {
        "court.appeal": {},
      }
    },
    "ca:nb": {
      "name": "New-Brunswick",
      "courts": {
        "court.appeal": {
          "variants": {
            "fr": {
              "name": "Cour d'appel"
            }
          }
        }
    }
```

Personally, I am torn. The "must conform exactly to the official standard" part of me wants to only translate the court name in the bilingual jurisdictions, but the "user friendless is most important" part thinks that having every court translated makes the interface much more user friendly, at no cost.

What do you guys think?

**Comment by Droitslinguistiques** [comment]
@fbennett  @georgd  I'd be very interested in your thoughts on this.

For user display purposes, should all courts of a bilingual jurisdiction be translated, or only the ones within a bilingual subjurisdiction?

One favors conformity to the official names, but the other favours ease of user access.

**Comment by fbennett** [comment]
I read your initial note, wasn't struck by a clear answer, and time passed. I think this is up to you, since you're in a better position to judge the attitudes and needs of users in Canada. It seems like imposing a fixed solution to all jurisdictions with multilingual requirements would create frictions at some point.

**Comment by Droitslinguistiques** [comment]
Fair enough. 

I'll close this issue and leave it as is for now then. Adding french translations of english only court names would increase the size of desc file quite a bit, so I don't want to do that unless there is a need for it.

Tests of Juris-M and the McGill style are rolling out with law school librarians in Canada this week, so I'm sure I'll get a lot more feedback and be able to re-evaluate down the line.

**Comment by georgd** [comment]
Sorry for answering late and on a closed issue. Besides the questions of user attitudes and file sizes: could there be a chance that the `name` value appears in a citation? Is there a situation where the processor picks or falls back to the `name` value? If so, I’d definitely not use it for jurisdictions which don’t use that language.

**Comment by fbennett** [comment]
If "abbrevs" is set in the language's array under the "langs" segment, the language will be used in citations, and "name" will be the fallback for "abbrev." If an "abbrev" value is given for each entry, the "name" value will not appear in citations, and will be used only in the UI (if "ui" is set in the language's array under "langs").

**Comment by georgd** [comment]
Thanks, @fbennett 

So, the citation side is not an issue as the abbrevs are defined in the `ca` file.

I don’t think that the size argument counts here. If I’m not mistaken, the size of the desc file is irrelevant. The UI strings are in the map files and the desc file isn’t transferred to the end user. The way the map files are organised, I think it doesn’t matter if a `name` string is used for one province alone or for all. I haven’t completely deciphered it yet but it looks as if each jurisdiction just points to the name string by means of an array index (I can’t verify as the `jurisupdate` command returns an error and it’s too late here to trace it down now). If that’s true, it’s irrelevant if the jurisdiction points to index `0` or `1` or even `31` from the array of name strings. And three more name strings for those courts that have no French name variant yet increase the map file size by few more bytes only.
