### ISSUE TITLE
Special reporter citations in AT, CH and DE

### ISSUE THREAD

**Issue by georgd** [Juris-M/legal-resource-registry#34]
# Citing from official reporters of supreme federal courts

Decisions of the supreme federal courts of these three countries are cited in a special way if only cited from the official reporter and I’m not sure how to prepare this in CSL-M and the LRR.

Case citation here usually includes (at least):
- court abbreviation
- docket no.
- reporter (abbreviated)
- reporter no./vol./year

Ex. of a normal citation: AT case (with parallel citation to official reporter):

`VfGH B 990/09, RdM 2010/61, 59 (Potacs) = VfSlg 18.966/2009.`

Components:
- Court abbrev (`VfGH`)
- docket no. (`B 990/09`)
- reporter (`RdM`)
- reporter year + vol. (`2010/61`)
- reporter page (59)
- commenter (Potacs)
- official reporter (`VfSlg`)
- official reporter no. + year. (`18.966/2009`)

Citing a case only from the official reporter looks like this:
`VfSlg 18.950/2009.`

Components: 
- official reporter (`VfSlg`)
- reporter no. + year (`18.950/2009`)

I’m absolutely not sure, how tho handle this.

In the juris-at-desc.json, would I extend the `"jurisdictions": "at"` object by the following for the two official reporters that would be treated in this way?

```
"container-title": {
        "VfSlg": "!authority>>>VfSlg",
        "VwSlg": "!authority>>>VwSlg"
      }
```

And how would I do it in the csl-file to discern between non-official and official reporters and between official reporters when cited alone and official reporters in a parallel citation?

# Non-official reporters needing special treatment

Traditionally, when citing a published case, the decision date is omitted, and in Germany usually also the docket no. isn’t used. Now, some reporters (one of them a very prominent one) are organised in a way that makes it necessary to add the decision date for ensuring findability.

A solution might be to simply leave away date (and docket no.) from entries in Juris-M but then, the more user-friendly citation styles require always to add the decision date. Also, for the purpose of organising the Juris-M database, decision date and dockt no. are very helpful.

Do you have an idea how to handle this?

**Comment by fbennett** [comment]
On the first issue, this is a problem very similar to "vendor-neutral" citations in US law. The way we handle it there is to set the official, court-specific court code in ``juris-desc`` as ABBREV (which is "compiled" to ``institution-entire`` in the abbrevs records, and called from CSL-M with ``form="short"``), and then invoke the ``form="short"`` version of the court name in its jurisdiction context when:
* there is no reporter;
* there is no volume number; and
* there is a "yearAsVolume" value

There are about a dozen US state-level jurisdictions that are handled in this way.

On the second question ... I'll have to think about this. If I understand correctly, it's kind of the inverse of our suppress-by-journal abbreviation hackery (that is, for a small subset of journals, additional information should be included)?

**Comment by fbennett** [comment]
On that second question (inclusion of the date only in cites to particular reporters), I can think of a couple of possible approaches. One, which we've used to cover the silly variety of cite forms described in the Bluebook for US jurisdictions, would be to use different field assignments for these reporters, such as by putting the journal name in the Archive field. It's an ugly hack, awkward to explain and prone to error, and if there is just one variant, hard to justify.

Another approach, which I've considered for the US case but haven't decided on yet, would be to reserve a special variable named something like ``reference-type``, with an integer value. That could then be tested for content to control the cite form. Adding the variable to the CSL-M schema would be simple enough. The question would be whether the approach would be workable for users.

A third approach might be to do something similar, but by embedding a flag in the journal abbreviation. The disadvantage there would be that the hint or flag would be activated only when the journal name is rendered, so (since citations are rendered front-to-back), it could not be used to control output that precedes the journal name. It would therefore not work for all conceivable use cases; but it would have the advantage of being totally transparent to the user: such references would "just work."

Not sure which of those is the best fit. What do you think? Other ideas also very welcome, of course.

**Comment by georgd** [comment]
> On the first issue, this is a problem very similar to "vendor-neutral" citations in US law. The way we handle it there is to set the official, court-specific court code in `juris-desc` as ABBREV (which is "compiled" to `institution-entire` in the abbrevs records, and called from CSL-M with `form="short"`), and then invoke the `form="short"` version of the court name in its jurisdiction context when:
> 
> * there is no reporter;
> * there is no volume number; and
> * there is a "yearAsVolume" value

Thank you! I got something that seems to work. Is the following about what you mean?

- in juris-at-desc.json:

```json
"vfgh": {
  "name": "Verfassungsgerichtshof",
  "ABBREV": "VfGH",
  "abbrev": "VfSlg",
  "variants": {
    "enIBFD": {
      "abbrev": "VfGH [Constitutional Court]"
    }
  }
},
```

- in juris-at.csl:

```xml
<choose>
  <if>
    <conditions match="all">
      <condition variable="container-title" match="none"/>
      <condition variable="volume" match="none"/>
      <condition variable="collection-number" match="any"/>
    </conditions>
    <names variable="authority">
      <name/>
      <institution institution-parts="short">
        <institution-part name="short"/>
      </institution>
    </names>
  </if>
  <else>
    <group no-repeat="authority">
      <names variable="authority">
        <name/>
        <institution form="short"/>
      </names>
    </group>
  </else>
</choose>
```

I have doubts if this would work for Germany. There, the _Federal Court of Justice_ has two official collections, one for private law and the other for criminal law matters.

**Comment by georgd** [comment]
> On that second question (inclusion of the date only in cites to particular reporters), I can think of a couple of possible approaches. One, which we've used to cover the silly variety of cite forms described in the Bluebook for US jurisdictions, would be to use different field assignments for these reporters, such as by putting the journal name in the Archive field. It's an ugly hack, awkward to explain and prone to error, and if there is just one variant, hard to justify.

As you say — ugly, awkward, and error prone but the easiest one to implement. 

> Another approach, which I've considered for the US case but haven't decided on yet, would be to reserve a special variable named something like `reference-type`, with an integer value. That could then be tested for content to control the cite form. Adding the variable to the CSL-M schema would be simple enough. The question would be whether the approach would be workable for users.

This could work. In the case of Germany, a flag-like variable would be enough. (BTW, what’s the `admin` flag meant for?) — The workability for users is probably not so bad as it’s just one value that could be set for German cases (At least not worse than putting a handful of journal titles in the archive field).

> A third approach might be to do something similar, but by embedding a flag in the journal abbreviation. The disadvantage there would be that the hint or flag would be activated only when the journal name is rendered, so (since citations are rendered front-to-back), it could not be used to control output that precedes the journal name. It would therefore not work for all conceivable use cases; but it would have the advantage of being totally transparent to the user: such references would "just work."

:D I like it when it "just works", but in this case it wouldn’t. The additional information is to be added _before_ the journal name.

> Not sure which of those is the best fit. What do you think? Other ideas also very welcome, of course.

I’d prefer the third one, of course, the least attractive is number one. I’ll still have to think a bit.

**Comment by fbennett** [comment]
We _might_ be able to get the third approach to work across the whole citation. The processor pulls the item at the beginning of the run, and if I've done things correctly, the item data remains untouched internally for the remainder of the citation run. The processor renders the citation once for disambiguation before rendering for display, so if the variable is added to the item internally, it should be available at the start of the rendering pass. I'll play with it and see. If it works, we can extend the markup syntax with a `+` element to complement the existing `!` suppression element.

**Comment by georgd** [comment]
That sounds good. Just to make sure – We’d be able to use the flag in one module for certain formatting in one style-module and just ignore it in another localised one?

**Comment by fbennett** [comment]
Yes. If it works, it will feed a variable (like reference-type or so) that
can be tested for an integer. Without any testing, it will have no effect.

**Comment by georgd** [comment]
Thinking more about it, this could also help with the remaining part of the first question – the case of the German Federal Court of Justice with two "official" reporters.

**Comment by fbennett** [comment]
... aaand it's confirmed to work. I have a test, an extension to the CSL-M schema, and a processor patch in the queue. I'll push a new processor version after cleanup and confirmation. The initial syntax looks like this:
```
"Original Title": "#1>>>Orig. Title"
```
The hash + number must come at the beginning of the string, so:
```
"Original Title": "#1!authority>>>Orig. Title"
```
The hash feeds a variable `cite-form` that can be tested, so:
```
<choose>
  <if cite-form="1">
    <text value="Yippeeee!"/>
  </if>
</choose>
```
The `cite-form` variable is only valid for testing. Attempts to render it with `cs:text` are invalid on the schema.

**Comment by fbennett** [comment]
> Thinking more about it, this could also help with the remaining part of the first question – the case of the German Federal Court of Justice with two "official" reporters.

Yes, you could go either way with those---either testing for the absence of a Reporter and presence of a YearAsVolume and Page, or relying on a cite-form value registered as the Reporter abbreviation.

**Comment by georgd** [comment]
Thank you, that’s really great!

**Comment by fbennett** [comment]
The release with support for cite-form is spooling up now, for Mac and Linux. The Windows release will go up tomorrow morning (JST).

**Comment by fbennett** [comment]
> Traditionally, when citing a published case, the decision date is omitted, and in Germany usually also the docket no. isn’t used. Now, some reporters (one of them a very prominent one) are organised in a way that makes it necessary to add the decision date for ensuring findability.

Can you provide a pair of examples, one showing the "normal" form, and one showing the form with the decision date included? I'm working on some documentation for the LRR, and I'll need to cover why the #/cite-form hack is needed. An illustration will make it very simple to explain.

**Comment by georgd** [comment]
"Normal" form — decision of the German Federal Administrative Court (BVerwG), found in reporter "NVwZ" from 1999, on page 296:

`BVerwG, NVwZ 1999, 296.`

"Special case", same decision (of type "Beschluss") found in reporter "Buchholz", section 310, related to § 65 VwGO, decision no. 131, p.2:

`BVerwG, Beschl. v. 9.1.1999 – Buchholz 310 § 65 VwGO Nr. 131, S. 2.`

The reporter is a looseleaf collection, republished every five years with the same systematic. Thus, it’s impossible identifying the very case from the reporter data: you will find a case no. 131 in section 310 in other Buchholz volumes as well.

**Comment by fbennett** [comment]
Thanks for this! I've used the case as an example in the description. There is still a lot of work to do on the document, but I think it will make the overall system easier for people to grasp and work with.
