### ISSUE TITLE
jurisupdate fails

### ISSUE THREAD

**Issue by georgd** [Juris-M/legal-resource-registry#37]
Something’s going wrong with my current version of juris-de-desc.json (see PR).

I can‘t find anything invalid – neither non-ASCII-chars in keys, nor illegal whitespace.

```
$ jurisupdate -j de
Using /Users/gduffner/Documents/dev/legal-resource-registry/src as path for descriptive jurisdiction files
Will read descriptive jurisdiction files from: /Users/gduffner/Documents/dev/legal-resource-registry/src
Will write abbreviation files to: /Users/gduffner/Zotero/juris-abbrevs
Will write compact jurisdiction files to: /Users/gduffner/Zotero/juris-maps
de
Writing /Users/gduffner/Zotero/juris-abbrevs/auto-de.json
Writing /Users/gduffner/Zotero/juris-abbrevs/auto-de-deAlt.json
Writing /Users/gduffner/Zotero/juris-abbrevs/auto-de-enIBFD.json
ERROR: Unexpected token b in JSON at position 0
```

**Comment by georgd** [comment]
@fbennett could you please have a look at this? I’m trying to create a proper style-module for DE but nothing’s working there and I want to exclude an issue with the abbreviations first.

**Comment by fbennett** [comment]
Sorry for missing this. Will take a look right away.

**Comment by fbennett** [comment]
I merged the PR and it works here. I also tried pulling the master branch from your fork, and that works as well. From the code of the script, it looks like it's failing on a write of `./juris-maps/versions.json` in your data directory. The script reads and parses that file, updates it, then serializes it back to disk. The script should handle a parse failure by rebuilding the file, but it currently doesn't. Check the file, if it's not good JSON, that's our issue, and I'll fix the script to handle it properly.

**Comment by fbennett** [comment]
I've pushed some changes to the script that should catch any parsing errors, both in `juris-maps/versions.json` and in map files that are not overwritten by the call to the script. The error messages should provide some meaningful guidance.

**Comment by fbennett** [comment]
The revision should help, but the logic isn't very elegant for global updates, where it repeatedly parses all files when updating each jurisdiction. I'll look at cleaning that up, but the current master should work for you.

**Comment by fbennett** [comment]
I've pushed another (and final, pending feedback) revision to rationalize updates. With the latest commits, it validates all map files, regenerating `versions.json` if necessary, then updates only the files that will change.

**Comment by georgd** [comment]
Great, thank you! the error is gone now.

**Comment by fbennett** [comment]
I've made [a change](https://github.com/Juris-M/citeproc-test-runner/commit/f4250ab978fde73a1d548dcfd87c4ead8dd1f02f) in `citeproc-test-runner` to proceed to the next text when the -k option is used, instead of rerunning the whole set. It will save time when a single style edit causes a large number of style tests to (incorrectly) fail for the same reason.
