### ISSUE TITLE
Can’t update eu.int

### ISSUE THREAD

**Issue by georgd** [Juris-M/legal-resource-registry#4]
`jurisupdate -t descriptive-to-compact -j eu.int` returns an error: 
```
ERROR: invalid court ID "ecj~chamber.1" in jurisdiction eu.int:cjeu
```
Is it the tilde or the period?

**Comment by fbennett** [comment]
Late picking this up, sorry. It's the tilde. I've fixed the upstream source to allow that, and the file now processes okay.

**Comment by georgd** [comment]
Even very much later picking up. I confirm it’s fixed. Thank you!
