### ISSUE TITLE
Suboptimal changes to eu.int

### ISSUE THREAD

**Issue by georgd** [Juris-M/legal-resource-registry#6]
Searching for the reason of https://github.com/Juris-M/jurism-abbreviations/issues/1 I stumbled upon commit 949e301fa3c543f79c78efe07bab369ce8648051 which does several things that are not optimal or even wrong:

- In the courts section of the `cjeu` jurisdiction, `ecj` is marked to ignore court which can’t be correct, in my opinion — and which is the reason, the German abbreviation got lost in auto-eu.int-de.json.
- The naming of the jurisdiction `eu.int/cjeu` and the court `ecj` got confused: the jurisdiction `eu.int/cjeu` is, in English, the "Court of Justice of the European Union", the court is the "European Court of Justice". In French, the jurisdiction is "Cour de Justice de l’Union Européenne" and the court is "Cour de Justice".
- Switching from French names to English might be questionable. English has no precedence over French or any other of the 24 official languages in the Union (since this year it doesn’t even belong to the major native languages). On the other hand, French is the sole working language of the CJEU.

**Comment by p-heckler** [comment]
I am going through some files and wondering the same thing regarding names, especially for international jurisdictions such as the ICJ, ITLOS, etc. Would it be valid to put alternative languages on the name tag like this? 
`"name": "court of Justice of the European Union",`
`"name:fr": "Cour de justice de l'Union européenne"`

**Comment by fbennett** [comment]
Closing this, as I think the issues raised here have been addressed. If that's mistaken, just ping and I'll reopen.
