### ISSUE TITLE
ECJ chambers on wrong hierarchical level

### ISSUE THREAD

**Issue by georgd** [Juris-M/legal-resource-registry#7]
The chambers of the ECJ are listed as courts in the jurisdiction `cjeu`, which is wrong. They’re divisions of the _court_ ECJ. Generally, I don’t think they fit in here at all as the different traditions compose them with different punctuation or parenthesis settings:

Currently, the abbrevs-file produces in English:
> Court of Justice First Chamber

French citation rules require:
> CJUE, 4ᵉ ch.

Austrian citation rules regularly only put the Grand Chamber (which currently is missing):
> EuGH (GK)

**Comment by fbennett** [comment]
The delimiter ``~`` is how I have designated court chambers in the court keys. So although these are siblings of first-class courts in the descriptive schema, they are meant to signify a division. Expressing the relation as a nested hierarchy in the schema would be cumbersome, at least at this stage.

Assuming that the local form of citation for ECJ judgments is determined by the target audience, not the case itself, Jurism can cope with this pretty easily. In the current setup, style modules are selected by filename, where ``juris-us.csl`` is the default US style, and ``juris-us-IndigoDev.csl`` is the "IndigoDev`` alternative. There is not limit to the number of permissible variants, and the parent style can select the preferred variant in a ``cs:style-options`` in the style's default locale, falling back to the default for the jurisdiction, and then to the US. If alternative abbreviations are also required, those can be configured to follow the style-module alternative.

**Comment by georgd** [comment]
> The delimiter `~` is how I have designated court chambers in the court keys. So although these are siblings of first-class courts in the descriptive schema, they are meant to signify a division. Expressing the relation as a nested hierarchy in the schema would be cumbersome, at least at this stage.

Thanks for the explanation. I was confused by the missing German abbreviation and didn’t correctly relate the court name with the abbreviation.

CSLm has a `division` variable that’s currently not visible in the interface. Do you plan to deprecate it or will it make it to the interface?

**Comment by fbennett** [comment]
Sorry for the late response. The ``division`` variable does come in handy when the jurisdiction map is coarse-grained, I'm planning to leave in in there. Is it okay to close this issue, or are adjustments still needed?
